config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'home_pages#top'
  get    'sessions/new'
  get    '/signup',                to: 'users#new'
  get    '/login',                 to: 'sessions#new'
  post   '/login',                 to: 'sessions#create'
  delete '/logout',                to: 'sessions#destroy'

  get     'users/:id/likes',       to: 'users#likes'
  post    'users/guest_sign_in',   to: 'users#new_guest' 
  get     'posts/ranking',         to: 'posts#ranking'
  resources :posts,               only: [:new, :index, :show, :edit,:update, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:create, :destroy,:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :icon
  has_many :likes,    dependent: :destroy
  has_many :liked_posts, through: :likes, source: :user
  has_many :posts,    dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum:15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 1.hours.ago
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def icon_image
    icon.variant(resize_to_fill: [50,50])
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー',email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end




  private

    def downcase_email
      self.email = email.downcase
    end


    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :index]
  before_action :check_guest,    only: [:edit, :update, :following, :followers]
  
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page],per_page: 12)
  end

  def create
    @user = User.new(user_params)
    @user.icon.attach(params[:user][:icon])
    if @user.save
      @user.send_activation_email
      flash[:info] = "メールアドレスを確認し、ログインしてください"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:success] = "ユーザー情報を更新しました"
     redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url
  end

  def likes
    @user=User.find_by(id: params[:id])
    @likes=Like.where(user_id: @user.id).paginate(page: params[:page],per_page: 12)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def new_guest
    user = User.guest
    log_in user
    flash[:success] =  'ゲストユーザーとしてログインしました。'
    redirect_to root_path
  
  end


  
private

  def user_params
    params.require(:user).permit(:name, :email, :password, 
                                 :password_confirmation,:icon)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f|%>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする" , class: "btn btn-dark" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow'%>
  <% else %>
    <%= render 'follow' %>
  <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name, "名前" %>
  <%= f.text_field :name, class: 'form-control' %>
          
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email, class: 'form-control' %>
         
  <%= f.label :password, "パスワード(6文字以上)" %>  
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード(確認)" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
          
  <%= f.submit yield(:button_text), class: "btn btn-dark" %>
<% end %>

app/views/users/_like.html.erb
<% if Like.find_by(user_id: current_user.id, post_id: post.id) %>
  <%= link_to post_like_path(post.id,post), method: :delete, remote: true do %>
    <span class="fa fa-heart like-btn-unlike"></span>
  <% end %>
<% else %> 
  <%= link_to post_likes_path(post), method: :post, remote: true do %>
    <span class="fa fa-heart like-btn"></span>
  <% end %>
<% end %>
<%= post.likes.length %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除" , class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
<div class="icon">
  <% if user.icon.attached? %>
    <%= image_tag user.icon_image %>
  <% else %>
    <%= image_tag("default_user.jpg", size: 50)%>
  <% end %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
    <%= link_to "削減", user, method: :delete,
                                data: { confirm: "削減しますか？" } %>
  <% end %>
</div>
</li>
  

app/views/users/edit.html.erb
<% provide(:button_text, '更新') %>
<div class="container">
  <div class="edit-top">
    <h1>ユーザー編集</h1>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: 'form-control' %>
 
        <%= f.label :icon, "プロフィール画像" %>
        <%= f.file_field :icon, placeholder: "アイコン" %>
          
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>
         
        <%= f.label :password, "パスワード(6文字以上)" %>  
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード(確認)" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
          
        <%= f.submit yield(:button_text), class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="login-top">
    <h1>ユーザー一覧</h1>
  </div>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/likes.html.erb
  <div class="container">
    <div class="row">
      <h1>
        <div class="icon">
          <% if @user.icon.attached? %>
            <%= image_tag @user.icon_image %>
          <% else %>
            <%= image_tag("default_user.jpg", size: 50)%>
          <% end %>
        </div>
        <div class="profile-name">
          <%= @user.name %>
        </div>
      </h1>
      <div class="user-show-menu">
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
      
        <%= render 'follow_form' if logged_in? %>
          <% if @user.posts.any? %>
            <%= link_to "投稿一覧", @user, class: "posts-likes" %>
            <%= link_to "いいね一覧", "/users/#{@user.id}/likes", class: "posts-likes" %>
            <% @likes.each do |like| %>
            <% post = Post.find_by(id: like.post_id) %> 
            <li class="posts">
              <%= render post %>
            </li>
            <% end %>
          <% end %>
            <div class="col-md-12">
              <%= will_paginate @likes %>
            </div> 
        </div>
    </div>
  </div>

app/views/users/new.html.erb
<% provide(:button_text, '作成') %>
<div class="container">
  <div class="signup-top">
    <h1>新規登録</h1>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <h1>
      <div class="icon">
        <% if @user.icon.attached? %>
          <%= image_tag @user.icon_image %>
        <% else %>
          <%= image_tag("default_user.jpg", size: 50)%>
        <% end %>
        <div class="profile-name">
          <%= @user.name %>
        </div>
      </div>
      </h1>
      <div class="user-show-menu">
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
          <%= render 'follow_form' if logged_in? %>
          <% if @user.posts.any? %>
            <%= link_to "投稿一覧", @user, class: "posts-likes" %>
            <%= link_to "いいね一覧", "/users/#{@user.id}/likes", class: "posts-likes" %>
            <li class="posts">
              <%= render @posts %>
            </li>
            <div class="col-md-12">
              <div class="paginate">
                <%= will_paginate @posts %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="show-follow-icon icon">
      <% if @user.icon.attached? %>
        <%= image_tag @user.icon_image %>
      <% else %>
        <%= image_tag("default_user.jpg", size: 50)%>
      <% end %>
      </div>
      <div class="show-follow-name">
        <h2><%= @user.name %></h2>
      </div>
      <%= render 'shared/stats' %>
    </div>
    <div class="col-md-8">
      <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>