config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'home_pages#top'
  get    'sessions/new'
  get    '/signup',                to: 'users#new'
  get    '/login',                 to: 'sessions#new'
  post   '/login',                 to: 'sessions#create'
  delete '/logout',                to: 'sessions#destroy'

  get     'users/:id/likes',       to: 'users#likes'
  post    'users/guest_sign_in',   to: 'users#new_guest' 
  get     'posts/ranking',         to: 'posts#ranking'
  resources :posts,               only: [:new, :index, :show, :edit,:update, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:create, :destroy,:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :likes,    dependent: :destroy
  has_many   :liked_users, through: :likes, source: :user
  has_many   :comments, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name,    presence: true, length: { maximum:50 }
  validates :content, presence: true, length: { maximum:140 }
  validates :image,   presence:true,   
                      content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "有効な画像形式である必要があります" },
                      size:         { less_than: 5.megabytes,
                                      message: "5MB未満である必要があります" }
  def display_image
    image.variant(resize_to_fill:[280,600])
  end

  def like_by?(user)
    likes.where(user_id: user_id).exist?
  end
  def self.sort_like
    Post.all.sort{|a,b| b.liked_users.count <=> a.liked_users.count}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :index, :create, :destroy]
  before_action :correct_user,   only: [:destroy, :edit, :update]
  before_action :check_guest,    only: [:new, :index, :create, :update, :edit, :destroy]

  def new
    @post = current_user.posts.build if logged_in?
  end

  def index
    @feed_items = current_user.feed.paginate(page: params[:page],per_page: 12) if logged_in?
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(5)
    @comment = @post.comments.build(user_id: current_user.id) if current_user
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to posts_url
    else
      @feed_items = current_user.posts.build(post_params)
      render 'posts/new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
     flash[:success] = "投稿情報を更新しました"
     redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] ="投稿を削除しました"
    redirect_to request.referrer || posts_url
  end

  def ranking
    @posts = Post.sort_like.paginate(page: params[:page],per_page: 12)
  end

  private

    def post_params
      params.require(:post).permit(:name, :content, :image)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end      
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_comment_list.html.erb
  <% @comments. each do |comment| %>
  <div class="col-md-12">
    <div class="comment_list">
      <%= comment.user.name %>
      <div class="comment-text">
        <%= comment.text %>
      </div>
      <div class="comment-delete">
        <% if current_user?(comment.user) %>
          <%= link_to "削除", post_comment_path(@post, comment), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %>
        <% end %>
      </div>      
    </div>
  </div>
  <% end %>

app/views/posts/_post.html.erb
<div class="post-layout">
  <div class="col-md-4">
    <div class="timeline">
      <div class="border-img">
        <%= link_to image_tag(post.display_image, alt: "home-layout-image"), post_path(post.id) %>
      </div>
      <div class="border-layout">
        <div class="timeline-icon icon">
          <% if post.user.icon.attached? %>
            <%= image_tag post.user.icon_image %>
          <% else %>
            <%= image_tag("default_user.jpg", size: 50)%>
          <% end %>
        </div>
        <div class="timeline-name">
          <%= link_to post.user.name, post.user %>
        </div>
        <div class="timeline-like">    
          <div id="like-<%= post.id%>">
            <%= render partial: "users/like", locals: { post: post } %>
          </div>
        </div>
        <% if current_user?(post.user) %>
        <div class="timeline-delete">
          <%= link_to "削除", post, method: :delete,
                                      data: { confirm: "削除しますか?" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>投稿編集</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @post, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :name, "オススメのアプリ名" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :content, "アプリのオススメポイント" %>
        <%= f.text_area :content %>
      </div>
      <span class="image">
        <%= f.file_field :image %>
      </span>

      <%=f.submit "投稿する", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
  <div class="container">
    <div class="row">
      <h1>タイムライン</h1>
        <%= render 'shared/feed' %>
    </div>
  </div>

app/views/posts/new.html.erb
<div class="container">
  <h1>新規投稿</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_with(model: @post, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
      <div class="field">

        <%= f.label :name, "オススメのアプリ名" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :content, "アプリのオススメポイント" %>
        <%= f.text_area :content %>
      </div>
      <span class="image">
        <%= f.label :image, "ホーム画面のレイアウト" %>
        <%= f.file_field :image %>
      </span>

      <%=f.submit "投稿する", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#post_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("最大ファイルサイズは5MBです。より小さいファイルを選択してください。");
      $("#post_image").val("");
    }
  });
</script>

app/views/posts/ranking.html.erb
<div class="container">
  <div class="row">
    <h1>投稿一覧</h1>
		<div class="index-btn">
      <a class="btn btn-lg btn-default" href="/" role="button">新着順</a>
      <a class="btn btn-lg btn-primary" href="/posts/ranking" role="button">人気順</a>
		</div>
    <%= render @posts %>
		<div class="col-md-12">
			<div class="paginate">
				<%= will_paginate @posts%>
			</div>
		</div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts-show" >
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="post-layout">
          <%= image_tag @post.display_image %>
        </div>
      </div>
      <div class="col-md-4">
      <div class="show-layout">
        <div class="icon">
          <% if @post.user.icon.attached? %>
            <%= image_tag @post.user.icon_image %>
          <% else %>
            <%= image_tag("default_user.jpg", size: 50)%>
          <% end %>
        </div>
        <div class="show-user-name">
          <%= link_to @post.user.name, @post.user %>
        </div>
        <div id="like-<%= @post.id%>">
          <%= render partial: "users/like", locals: { post: @post } %>
        </div>
      </div>
        <div class="show-name">
          <h2>オススメアプリ</h2>
          <%= @post.name %>
        </div>
        <div class="show-content">
          <h2>オススメポイント</h2>
          <%= @post.content%>
        </div>
        <% if current_user?(@post.user) %>
        <div class="timeline-edit">
          <%= link_to "編集する", edit_post_path(@post) %>
        </div>
        <% end %>
        </div>
        <div class="col-md-4">
          <% if current_user %>
            <%= form_with(model: [@post,@comment], class: "message-form", local: true) do |f| %>
              <%= f.text_area :text, class: "textbox", placeholder: "投稿へのコメントを入力する" %>
              <%= f.submit "送信する", class: "form_submit"%>
            <% end %>
          <% end %>
          <div id="comment_lists">
            <%= render 'comment_list' %>
          </div>
          <div class="more">
            <%= link_to_next_page @comments, 'もっと見る', remote: true, id: 'view_more' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$('#view_more').remove();
$('#comment_lists').append("<%= escape_javascript(render 'comment_list', object: @comments) %>");
$("#comment_lists").append("<%= escape_javascript(link_to_next_page(@comments, 'もっと見る', remote: true, id: 'view_more')) %>")