config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'home_pages#top'
  get    'sessions/new'
  get    '/signup',                to: 'users#new'
  get    '/login',                 to: 'sessions#new'
  post   '/login',                 to: 'sessions#create'
  delete '/logout',                to: 'sessions#destroy'

  get     'users/:id/likes',       to: 'users#likes'
  post    'users/guest_sign_in',   to: 'users#new_guest' 
  get     'posts/ranking',         to: 'posts#ranking'
  resources :posts,               only: [:new, :index, :show, :edit,:update, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:create, :destroy,:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <div class="main-logo">
        <%= link_to "viewhome",   root_path %>
      </div>
  </div>

<div class="collapse navbar-collapse" id="navbar">
	<ul class="nav navbar-nav">
    <% if logged_in? %>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "ユーザー編集", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "ログアウト", logout_path, method: :delete %>
          </li>
        </ul>
        <li><%= link_to "投稿する", new_post_path %></li>
        <li><%= link_to "タイムライン", posts_path %></li>
        <% if admin_user? %>
            <li><%= link_to "ユーザー一覧", users_path %></li>
        <% end %>
    <% else %>
      <li><%= link_to "新規登録",   signup_path %></li>
      <li><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %></li>
      <li><%= link_to "ログイン",   login_path %></li>
    <% end %>
  </ul>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Viewhome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <%= favicon_link_tag 'favicon.ico'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>